import { useEffect, useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, FileText, Globe2, Mail, SearchCheck, Send, Sparkles } from "lucide-react";
import { Link } from "wouter";

const steps = [
  { icon: Building2, label: "Utah registration", detail: "A founder registers a new business with Utah.", data: "New entity · public filing signal" },
  { icon: Globe2, label: "Public signal", detail: "The filing and public web context become a usable company signal.", data: "Entity record · landing page context" },
  { icon: SearchCheck, label: "PlainText research", detail: "The agent translates the company story and searches support programs.", data: "Grants.gov · USAspending · SBIR" },
  { icon: FileText, label: "Opportunity Map", detail: "Available government support is organized into a readable report.", data: "Amounts · requirements · evidence" },
  { icon: Mail, label: "Founder briefing", detail: "A concise briefing moves back to the founder through an appropriate channel.", data: "Opt-in report · plain-language actions" },
];

export default function HowItWorks() {
  const [active, setActive] = useState(0);
  useEffect(() => {
    const timer = window.setInterval(() => setActive((current) => (current + 1) % steps.length), 2600);
    return () => window.clearInterval(timer);
  }, []);
  const current = steps[active];
  return <div className="min-h-screen bg-ink text-white">
    <header className="border-b border-white/10"><div className="container flex h-16 items-center justify-between"><Link href="/" className="font-display text-xl font-semibold tracking-tight">PlainText<span className="text-lime">.legal</span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm text-white/65 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to site</Link></div></header>
    <main>
      <section className="border-b border-white/10 py-16 lg:py-24"><div className="container"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-lime/30 bg-lime/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.16em] text-lime"><Sparkles className="h-3.5 w-3.5" /> How it works</div><h1 className="mt-6 font-display text-5xl font-semibold leading-[.98] sm:text-7xl">A public signal becomes a founder briefing.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/62">Think of PlainText.legal as a translation layer between a company’s first public signal and the government support it may be able to use.</p></div></div></section>
      <section className="py-14 lg:py-20"><div className="container"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div className="lg:sticky lg:top-8 lg:self-start"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-lime">The process, in motion</div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[.04] p-6"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-lime text-ink"><current.icon className="h-5 w-5" /></div><div><div className="font-mono text-[10px] uppercase tracking-[.14em] text-lime">Step 0{active + 1} / 05</div><h2 className="mt-1 font-display text-2xl font-semibold">{current.label}</h2></div></div><p className="mt-6 text-[16px] leading-7 text-white/70">{current.detail}</p><div className="mt-6 border-t border-white/10 pt-4 font-mono text-xs text-white/45">{current.data}</div></div><div className="mt-5 grid grid-cols-5 gap-2" aria-label="Animation progress">{steps.map((step, index) => <button aria-label={`Show ${step.label}`} className={`h-1.5 rounded-full transition-colors ${index <= active ? "bg-lime" : "bg-white/15"}`} key={step.label} onClick={() => setActive(index)} type="button" />)}</div></div><div className="relative"><div className="absolute bottom-12 left-7 top-12 hidden w-px bg-lime/25 sm:block" />{steps.map((step, index) => { const Icon = step.icon; const isActive = index === active; return <div className={`relative mb-5 flex gap-5 rounded-2xl border p-5 transition-all duration-500 last:mb-0 ${isActive ? "border-lime/55 bg-lime/10 shadow-[0_0_45px_rgba(190,220,77,.08)]" : "border-white/10 bg-white/[.03]"}`} key={step.label}><div className={`relative z-10 grid h-14 w-14 shrink-0 place-items-center rounded-xl ${isActive ? "bg-lime text-ink" : "bg-white/10 text-lime"}`}><Icon className="h-5 w-5" />{isActive && <span className="absolute -right-1 -top-1 h-3 w-3 rounded-full bg-lime shadow-[0_0_0_5px_rgba(190,220,77,.15)]" />}</div><div className="min-w-0"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-lime">Node 0{index + 1}</div><h3 className="mt-1 font-display text-2xl font-semibold">{step.label}</h3><p className="mt-1 text-sm leading-6 text-white/55">{step.detail}</p><div className="mt-3 font-mono text-xs text-white/35">{step.data}</div></div>{index < steps.length - 1 && isActive && <span className="signal-travel absolute left-7 top-full z-20 h-3 w-3 rounded-full bg-lime shadow-[0_0_18px_rgba(190,220,77,.8)]" />}</div>; })}</div></div></div></section>
      <section className="border-t border-white/10 py-14"><div className="container"><div className="mx-auto max-w-3xl rounded-2xl border border-lime/25 bg-lime/10 p-6 text-center sm:p-10"><Send className="mx-auto h-6 w-6 text-lime" /><h2 className="mt-4 font-display text-3xl font-semibold">The end state is not a search result.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-white/65">It is a founder-ready explanation of what support exists, how much it may be worth, what must be verified, and what to do next.</p><div className="email-float mx-auto mt-8 max-w-md rounded-xl border border-white/15 bg-ink/70 p-4 text-left shadow-[0_15px_45px_rgba(0,0,0,.18)]"><div className="flex items-center justify-between gap-3 border-b border-white/10 pb-3"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-lime text-ink"><Mail className="h-4 w-4" /></div><div><div className="text-xs font-semibold text-white">PlainText.legal</div><div className="text-[10px] text-white/45">to founder@example.com</div></div></div><span className="font-mono text-[10px] text-lime">READY</span></div><div className="pt-3"><div className="text-xs font-semibold text-white">Your Government Opportunity Map is ready</div><div className="mt-1 text-xs leading-5 text-white/55">2 opportunities · up to $2.5M surfaced · 4 things to verify</div></div></div><Link href="/#hero-search" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-lime px-4 py-3 text-sm font-semibold text-ink hover:bg-lime/90">Try a founder scan <ArrowLeft className="h-4 w-4 rotate-180" /></Link></div></div></section>
    </main>
  </div>;
}
