import { Building2, Globe2, MailCheck, SearchCheck, ArrowRight } from "lucide-react";
import { Link } from "wouter";

const stages = [
  { icon: <Building2 className="h-5 w-5" />, title: "A Utah business or domain signal appears", detail: "A newly formed Utah company enters a monitored public-record list, or a licensed domain event arrives from a data provider." },
  { icon: <Globe2 className="h-5 w-5" />, title: "Public company context is interpreted", detail: "PlainText reads available registration details and accessible website context to build a careful first profile." },
  { icon: <SearchCheck className="h-5 w-5" />, title: "Support is researched and organized", detail: "The agent translates the company story into government language, then investigates live opportunities, historical awards, and R&D signals." },
  { icon: <MailCheck className="h-5 w-5" />, title: "A useful founder briefing is ready", detail: "The founder receives a prioritized Opportunity Map: grant dollars, requirements to verify, and practical next steps." },
];

export default function AutomationSection() {
  return <section className="border-b border-ink/10 bg-white py-20 lg:py-28" id="automation"><div className="container"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div className="lg:pt-8"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-moss">Automatic support discovery</div><h2 className="mt-4 max-w-md font-display text-5xl font-semibold leading-[.98]">Support research begins when a company does.</h2><p className="mt-6 max-w-sm text-[16px] leading-7 text-ink/60">Four signals become one clear founder briefing—without asking a newly formed company to know what to search for first.</p><Link href="/how-it-works" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-moss px-4 py-3 text-sm font-semibold text-white transition-colors hover:bg-moss/90">How it works <ArrowRight className="h-4 w-4" /></Link></div><div className="relative space-y-5 before:absolute before:bottom-8 before:left-7 before:top-8 before:w-px before:bg-moss/20">{stages.map((stage, index) => <article className="relative z-10 flex gap-5 rounded-2xl border border-ink/10 bg-paper p-6 shadow-[0_10px_30px_rgba(31,54,54,.04)]" key={stage.title}><div className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-moss text-white">{stage.icon}</div><div><div className="font-mono text-[10px] uppercase tracking-[.14em] text-moss">Step 0{index + 1}</div><h3 className="mt-2 font-display text-2xl font-semibold leading-tight">{stage.title}</h3><p className="mt-2 max-w-xl text-sm leading-relaxed text-ink/65">{stage.detail}</p></div></article>)}</div></div></div></section>;
}
