import { Building2, Globe2, MailCheck, SearchCheck } from "lucide-react";

const stages = [
  { icon: <Building2 className="h-4 w-4" />, title: "1. A public business or domain signal appears", detail: "A newly registered Utah entity appears in a monitored public Business Entity List, or a licensed new-domain signal arrives from a data provider." },
  { icon: <Globe2 className="h-4 w-4" />, title: "2. Public context is interpreted", detail: "The agent reads available filing details and a public landing page when one exists, then builds a cautious startup profile." },
  { icon: <SearchCheck className="h-4 w-4" />, title: "3. Support is researched and organized", detail: "It searches live Grants.gov and USAspending data, layers SBIR/STTR context, and creates a Government Opportunity Map." },
  { icon: <MailCheck className="h-4 w-4" />, title: "4. A useful introduction is ready", detail: "PlainText creates a report link and a concise founder briefing that can be delivered through an appropriate sourced outreach or partner channel." },
];

export default function AutomationSection() {
  return <section className="border-b border-ink/10 bg-white py-16" id="automation"><div className="container"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-moss">The event-driven vision</div><h2 className="mt-3 font-display text-4xl font-semibold leading-tight">What if support research began the moment a company begins?</h2><p className="mt-4 max-w-xl text-[16px] leading-7 text-ink/65">The long-term PlainText.legal product does not wait for a founder to know what to search. A new business signal starts a focused research run automatically, translating the company’s public context into the programs, evidence, and next steps worth reviewing.</p><div className="mt-7 rounded-xl border border-moss/20 bg-moss/5 p-4 text-sm leading-relaxed text-ink/75"><div className="flex items-center gap-2 font-semibold text-moss"><Building2 className="h-4 w-4" /> Utah public records can start the research</div><p className="mt-1">Utah’s Division of Corporations provides a public <a className="font-semibold underline decoration-moss/35 underline-offset-2 hover:text-moss" href="https://commerce.utah.gov/corporations/searches/" target="_blank" rel="noreferrer">Business Entity Search and customizable Business Entity List</a>. That public filing data is one reason newly formed LLCs often receive service offers. PlainText.legal can monitor a lawfully obtained business list, use the available company details and public web context, and prepare a first Opportunity Map automatically.</p><p className="mt-2 text-ink/60">New-domain signals come from licensed registrar, registry, or data-provider feeds. Any outreach uses source-appropriate contact channels and follows the applicable communications rules; the research itself does not depend on hidden WHOIS data.</p></div></div><div className="relative"><div className="absolute left-5 top-7 bottom-7 hidden w-px bg-moss/20 sm:block" />{stages.map((stage) => <div className="relative flex gap-4 py-4 first:pt-0 last:pb-0" key={stage.title}><div className="relative z-10 grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-moss text-white">{stage.icon}</div><div className="rounded-xl border border-ink/10 bg-paper p-4"><h3 className="font-semibold">{stage.title}</h3><p className="mt-1 text-sm leading-relaxed text-ink/60">{stage.detail}</p></div></div>)}</div></div><div className="mt-10 border-t border-ink/10 pt-5 text-sm leading-relaxed text-ink/55"><span className="font-semibold text-ink">Today:</span> founder-initiated scans run this same agent. <span className="font-semibold text-ink">Next:</span> monitored Utah public business records and licensed domain data can start the research automatically at formation or launch.</div></div></section>;
}
