import { ArrowUpRight, CalendarDays, DollarSign, Landmark, ShieldAlert } from "lucide-react";

export default function LiveGrantExample() {
  return <article className="relative mx-auto w-full max-w-lg self-center overflow-hidden rounded-2xl border border-ink/10 bg-white p-5 shadow-[0_24px_80px_rgba(31,54,54,.14)]">
    <div className="flex items-start justify-between gap-4 border-b border-ink/10 pb-4"><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-moss">Live Grants.gov record</div><div className="mt-1 font-mono text-xs font-semibold tracking-wide text-ink/60">SB-OEDCS-26-002</div></div><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-moss/10 text-moss"><Landmark className="h-5 w-5" /></div></div>
    <div className="py-4"><h2 className="font-display text-xl font-semibold leading-tight">Manufacturing &amp; Small Business Cybersecurity Resilience</h2><p className="mt-2 text-sm text-ink/60">U.S. Small Business Administration · posted Aug. 13, 2026</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-moss p-3 text-white"><div className="flex items-center gap-1.5 font-mono text-[9px] uppercase tracking-[.14em] text-white/70"><DollarSign className="h-3 w-3" /> Maximum award</div><div className="mt-1 font-display text-3xl font-semibold">$2.5M</div><div className="mt-1 text-[11px] text-white/75">Up to 2 awards</div></div><div className="rounded-xl bg-paper p-3"><div className="flex items-center gap-1.5 font-mono text-[9px] uppercase tracking-[.14em] text-ink/45"><CalendarDays className="h-3 w-3" /> Deadline</div><div className="mt-1 font-display text-xl font-semibold">Sep. 4</div><div className="mt-1 text-[11px] text-ink/55">2026 · 24-month period</div></div></div><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="flex gap-2"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-800" /><div><div className="text-xs font-bold text-amber-950">A useful agent flag</div><p className="mt-1 text-xs leading-relaxed text-amber-950/70">This is a real, active opportunity—but its official eligibility is limited to state entities, universities, or state designees in Indiana, Ohio, or Virginia. A Utah startup should treat it as adjacent context, not an application recommendation.</p></div></div></div></div>
    <a className="flex items-center justify-between rounded-lg bg-ink px-3 py-2.5 text-xs font-semibold text-white hover:bg-moss" href="https://www.grants.gov/search-results-detail/363586" target="_blank" rel="noreferrer">Open official record <ArrowUpRight className="h-3.5 w-3.5" /></a>
  </article>;
}
